apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: del-failed-jobs
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "delete"]

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: del-failed-jobs
  namespace: infra

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: del-failed-jobs
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: ClusterRole
  name: del-failed-jobs
subjects:
- kind: ServiceAccount
  name: del-failed-jobs
  namespace: infra
---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: del-failed-jobs
  namespace: infra
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: del-failed-jobs
          containers:
          - name: del-pods
            image: bitnami/kubectl:latest
            command:
              - sh
              - -c
              - kubectl delete jobs --field-selector status.successful=0 --all-namespaces